# ignored checks:
ignored:
  - DL3007 # Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag
  - DL3008 # Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
  - DL3013 # Pin versions in pip.
  - DL3016 # Pin versions in npm.
  - DL3059 # Multiple consecutive `RUN` instructions. Consider consolidation.
  - DL4000 # MAINTAINER is deprecated
  - DL4006 # Set the SHELL option -o pipefail before RUN with a pipe in it.
  - SC2174 # When used with -p, -m only applies to the deepest directory.
  - SC1091 # Not following: File not included in mock. // RUN . /root/.nvm/nvm.sh
  - SC2240 # warning: The dot command does not support arguments in sh/dash. Set them as variables.