name: "production"

on:
  push:
    tags: ['*']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ 'server', 'ui' ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: version
        id: version
        run: echo ::set-output name=git_tag::${GITHUB_REF#refs/tags/}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: add tag to ${{ matrix.image }} image
        uses: abronin/ecr-retag-action@v1
        with:
          repository: ${{ secrets.ECR_REGISTRY }}/namebazaar-${{ matrix.image }}
          tag: ${{ github.sha }}
          new-tags: ${{ steps.version.outputs.git_tag }}