name: "production"

on:
  push:
    tags: ['*']

jobs:
  build-and-push-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: version
        id: version
        run: echo ::set-output name=git_tag::${GITHUB_REF#refs/tags/}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

# this use 'base' image from QA workflow. This is not perfect, but first line from Dockerfile should tell you why:
# FROM namebazaar-base:latest AS builder
# it can't dynamically point to QA / prod
# the only one right solution is to not use BUILD_ENV in the project
# then this workflow will not build any image, but instead add new tag to existing one

# base registry doesn't exist
#      - name: Base image
#        uses: docker/build-push-action@v3
#        with:
#          push: false
#          file: docker-builds/base/Dockerfile
#          tags: |
#            namebazaar-base:${{ github.sha }}
#            namebazaar-base:latest

      - name: Server image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: docker-builds/base/Dockerfile
          tags: |
            ${{ secrets.ECR_REGISTRY }}/namebazaar-server:${{ steps.version.outputs.git_tag }}-prod
            ${{ secrets.ECR_REGISTRY }}/namebazaar-server:latest-prod
          build-args: |
            BUILD_ENV=prod

      - name: UI image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: docker-builds/ui/Dockerfile
          tags: |
            ${{ secrets.ECR_REGISTRY }}/namebazaar-ui:${{ steps.version.outputs.git_tag }}-prod
            ${{ secrets.ECR_REGISTRY }}/namebazaar-ui:latest-prod
          build-args: |
            BUILD_ENV=prod